In [5]:
import pandas as pd

# Dati della classifica
data = [
    {"posizione": 1, "provincia": "Bari", "punteggio": 744.3},
    {"posizione": 2, "provincia": "Barletta-Andria-Trani", "punteggio": 733.2},
    {"posizione": 3, "provincia": "Pescara", "punteggio": 732.8},
    {"posizione": 4, "provincia": "Livorno", "punteggio": 716.2},
    {"posizione": 5, "provincia": "Enna", "punteggio": 713.9},
    {"posizione": 6, "provincia": "Ancona", "punteggio": 710.2},
    {"posizione": 7, "provincia": "Trieste", "punteggio": 708.1},
    {"posizione": 8, "provincia": "Chieti", "punteggio": 699.5},
    {"posizione": 9, "provincia": "Catanzaro", "punteggio": 695.5},
    {"posizione": 10, "provincia": "Pesaro e Urbino", "punteggio": 692.8},
    {"posizione": 11, "provincia": "Brindisi", "punteggio": 690.9},
    {"posizione": 12, "provincia": "Potenza", "punteggio": 686.2},
    {"posizione": 13, "provincia": "Rimini", "punteggio": 684.1},
    {"posizione": 14, "provincia": "Campobasso", "punteggio": 676.6},
    {"posizione": 15, "provincia": "Venezia", "punteggio": 675.2},
    {"posizione": 16, "provincia": "Vibo Valentia", "punteggio": 672.5},
    {"posizione": 17, "provincia": "Imperia", "punteggio": 660.9},
    {"posizione": 18, "provincia": "Ascoli Piceno", "punteggio": 656.9},
    {"posizione": 19, "provincia": "Fermo", "punteggio": 654.6},
    {"posizione": 20, "provincia": "Macerata", "punteggio": 653.1},
    {"posizione": 21, "provincia": "Catania", "punteggio": 651.7},
    {"posizione": 22, "provincia": "Perugia", "punteggio": 649.7},
    {"posizione": 23, "provincia": "Reggio Calabria", "punteggio": 649.4},
    {"posizione": 24, "provincia": "Aosta", "punteggio": 646.4},
    {"posizione": 25, "provincia": "Crotone", "punteggio": 643.9},
    {"posizione": 26, "provincia": "Cagliari", "punteggio": 642.7},
    {"posizione": 27, "provincia": "Teramo", "punteggio": 642.3},
    {"posizione": 28, "provincia": "Napoli", "punteggio": 641.8},
    {"posizione": 29, "provincia": "Savona", "punteggio": 641.3},
    {"posizione": 30, "provincia": "Siena", "punteggio": 640.2},
    {"posizione": 31, "provincia": "Bolzano", "punteggio": 637.0},
    {"posizione": 32, "provincia": "La Spezia", "punteggio": 635.4},
    {"posizione": 33, "provincia": "Genova", "punteggio": 634.4},
    {"posizione": 34, "provincia": "Messina", "punteggio": 632.8},
    {"posizione": 35, "provincia": "L'Aquila", "punteggio": 629.9},
    {"posizione": 36, "provincia": "Isernia", "punteggio": 627.3},
    {"posizione": 37, "provincia": "Sassari", "punteggio": 627.0},
    {"posizione": 38, "provincia": "Nuoro", "punteggio": 624.5},
    {"posizione": 39, "provincia": "Salerno", "punteggio": 620.8},
    {"posizione": 40, "provincia": "Ravenna", "punteggio": 617.6},
    {"posizione": 41, "provincia": "Gorizia", "punteggio": 613.7},
    {"posizione": 42, "provincia": "Foggia", "punteggio": 613.4},
    {"posizione": 43, "provincia": "Matera", "punteggio": 613.1},
    {"posizione": 44, "provincia": "Cuneo", "punteggio": 612.4},
    {"posizione": 45, "provincia": "Trapani", "punteggio": 611.3},
    {"posizione": 46, "provincia": "Forlì-Cesena", "punteggio": 610.9},
    {"posizione": 47, "provincia": "Roma", "punteggio": 607.3},
    {"posizione": 48, "provincia": "Latina", "punteggio": 606.1},
    {"posizione": 49, "provincia": "Oristano", "punteggio": 604.5},
    {"posizione": 50, "provincia": "Viterbo", "punteggio": 603.4}
]

# Creazione del dataframe
clima = pd.DataFrame(data)

# Mostra i primi 5 record
clima

    posizione              provincia  punteggio
0           1                   Bari      744.3
1           2  Barletta-Andria-Trani      733.2
2           3                Pescara      732.8
3           4                Livorno      716.2
4           5                   Enna      713.9
5           6                 Ancona      710.2
6           7                Trieste      708.1
7           8                 Chieti      699.5
8           9              Catanzaro      695.5
9          10        Pesaro e Urbino      692.8
10         11               Brindisi      690.9
11         12                Potenza      686.2
12         13                 Rimini      684.1
13         14             Campobasso      676.6
14         15                Venezia      675.2
15         16          Vibo Valentia      672.5
16         17                Imperia      660.9
17         18          Ascoli Piceno      656.9
18         19                  Fermo      654.6
19         20               Macerata      653.1
20         21                Catania      651.7
21         22                Perugia      649.7
22         23        Reggio Calabria      649.4
23         24                  Aosta      646.4
24         25                Crotone      643.9
25         26               Cagliari      642.7
26         27                 Teramo      642.3
27         28                 Napoli      641.8
28         29                 Savona      641.3
29         30                  Siena      640.2
30         31                Bolzano      637.0
31         32              La Spezia      635.4
32         33                 Genova      634.4
33         34                Messina      632.8
34         35               L'Aquila      629.9
35         36                Isernia      627.3
36         37                Sassari      627.0
37         38                  Nuoro      624.5
38         39                Salerno      620.8
39         40                Ravenna      617.6
40         41                Gorizia      613.7
41         42                 Foggia      613.4
42         43                 Matera      613.1
43         44                  Cuneo      612.4
44         45                Trapani      611.3
45         46           Forlì-Cesena      610.9
46         47                   Roma      607.3
47         48                 Latina      606.1
48         49               Oristano      604.5
49         50                Viterbo      603.4

In [6]:
import pandas as pd
import json

# JSON dei dati
data_json = '''{
  "classifica": [
    {"posizione": 1, "variazione": "+4▲", "provincia": "Bergamo", "punteggio": 640.52, "altro": 1},
    {"posizione": 2, "variazione": "+1▲", "provincia": "Trento", "punteggio": 639.90, "altro": 239},
    {"posizione": 3, "variazione": "+10▲", "provincia": "Bolzano", "punteggio": 635.09, "altro": 594},
    {"posizione": 4, "variazione": "+5▲", "provincia": "Monza-Brianza", "punteggio": 632.50},
    {"posizione": 5, "variazione": "+13▲", "provincia": "Cremona", "punteggio": 626.33},
    {"posizione": 6, "variazione": "-5▼", "provincia": "Udine", "punteggio": 625.12, "altro": 1},
    {"posizione": 7, "variazione": "+3▲", "provincia": "Verona", "punteggio": 624.48},
    {"posizione": 8, "variazione": "+14▲", "provincia": "Vicenza", "punteggio": 622.09},
    {"posizione": 9, "variazione": "-7▼", "provincia": "Bologna", "punteggio": 621.99, "altro": 511},
    {"posizione": 10, "variazione": "+17▲", "provincia": "Ascoli Piceno", "punteggio": 620.07},
    {"posizione": 11, "variazione": "+6▲", "provincia": "Como", "punteggio": 619.69},
    {"posizione": 12, "variazione": "-4▼", "provincia": "Milano", "punteggio": 619.47, "altro": 25},
    {"posizione": 13, "variazione": "+27▲", "provincia": "Forlì-Cesena", "punteggio": 618.21},
    {"posizione": 14, "variazione": "+24▲", "provincia": "Lecco", "punteggio": 617.98},
    {"posizione": 15, "variazione": "+15▲", "provincia": "Siena", "punteggio": 615.83, "altro": 21},
    {"posizione": 16, "variazione": "-2▼", "provincia": "Pordenone", "punteggio": 615.28},
    {"posizione": 17, "variazione": "-13▼", "provincia": "Aosta", "punteggio": 615.03, "altro": 322},
    {"posizione": 18, "variazione": "+1▲", "provincia": "Padova", "punteggio": 614.13},
    {"posizione": 19, "variazione": "-7▼", "provincia": "Trieste", "punteggio": 613.78, "altro": 312},
    {"posizione": 20, "variazione": "-5▼", "provincia": "Brescia", "punteggio": 610.85},
    {"posizione": 21, "variazione": "-14▼", "provincia": "Modena", "punteggio": 607.39, "altro": 1},
    {"posizione": 22, "variazione": "+11▲", "provincia": "Varese", "punteggio": 606.37},
    {"posizione": 23, "variazione": "+23▲", "provincia": "Mantova", "punteggio": 605.33},
    {"posizione": 24, "variazione": "-4▼", "provincia": "Treviso", "punteggio": 605.19},
    {"posizione": 25, "variazione": "+12▲", "provincia": "Macerata", "punteggio": 602.59},
    {"posizione": 26, "variazione": "-15▼", "provincia": "Parma", "punteggio": 602.55, "altro": 24},
    {"posizione": 27, "variazione": "+7▲", "provincia": "Ravenna", "punteggio": 601.04, "altro": 11},
    {"posizione": 28, "variazione": "-12▼", "provincia": "Reggio Emilia", "punteggio": 598.87, "altro": 12},
    {"posizione": 29, "variazione": "+19▲", "provincia": "Lodi", "punteggio": 597.89},
    {"posizione": 30, "variazione": "-1▼", "provincia": "Sondrio", "punteggio": 597.64, "altro": 224},
    {"posizione": 31, "variazione": "-", "provincia": "Prato", "punteggio": 595.97},
    {"posizione": 32, "variazione": "+10▲", "provincia": "Novara", "punteggio": 595.00},
    {"posizione": 33, "variazione": "-7▼", "provincia": "Piacenza", "punteggio": 594.33, "altro": 111},
    {"posizione": 34, "variazione": "-13▼", "provincia": "Pisa", "punteggio": 593.77},
    {"posizione": 35, "variazione": "-11▼", "provincia": "Ancona", "punteggio": 591.50},
    {"posizione": 36, "variazione": "-30▼", "provincia": "Firenze", "punteggio": 590.45, "altro": 11},
    {"posizione": 37, "variazione": "+2▲", "provincia": "Cuneo", "punteggio": 588.84},
    {"posizione": 38, "variazione": "-13▼", "provincia": "Pesaro e Urbino", "punteggio": 588.54},
    {"posizione": 39, "variazione": "-11▼", "provincia": "Gorizia", "punteggio": 588.07, "altro": 14},
    {"posizione": 40, "variazione": "+9▲", "provincia": "Perugia", "punteggio": 585.85},
    {"posizione": 41, "variazione": "+4▲", "provincia": "Arezzo", "punteggio": 581.65, "altro": 1},
    {"posizione": 42, "variazione": "+9▲", "provincia": "Rimini", "punteggio": 579.98},
    {"posizione": 43, "variazione": "-", "provincia": "Pavia", "punteggio": 579.46},
    {"posizione": 44, "variazione": "-21▼", "provincia": "Cagliari", "punteggio": 578.10},
    {"posizione": 45, "variazione": "-1▼", "provincia": "Belluno", "punteggio": 576.79, "altro": 225},
    {"posizione": 46, "variazione": "-14▼", "provincia": "Venezia", "punteggio": 572.31},
    {"posizione": 47, "variazione": "+3▲", "provincia": "Fermo", "punteggio": 571.72},
    {"posizione": 48, "variazione": "+14▲", "provincia": "Terni", "punteggio": 568.88},
    {"posizione": 49, "variazione": "+6▲", "provincia": "Asti", "punteggio": 568.83},
    {"posizione": 50, "variazione": "+2▲", "provincia": "Biella", "punteggio": 568.02}
  ]
}'''

# Caricare il JSON
data = json.loads(data_json)

# Creare il DataFrame
qualità = pd.DataFrame(data["classifica"])

# Visualizzare il DataFrame
qualità

    posizione variazione        provincia  punteggio  altro
0           1        +4▲          Bergamo     640.52    1.0
1           2        +1▲           Trento     639.90  239.0
2           3       +10▲          Bolzano     635.09  594.0
3           4        +5▲    Monza-Brianza     632.50    NaN
4           5       +13▲          Cremona     626.33    NaN
5           6        -5▼            Udine     625.12    1.0
6           7        +3▲           Verona     624.48    NaN
7           8       +14▲          Vicenza     622.09    NaN
8           9        -7▼          Bologna     621.99  511.0
9          10       +17▲    Ascoli Piceno     620.07    NaN
10         11        +6▲             Como     619.69    NaN
11         12        -4▼           Milano     619.47   25.0
12         13       +27▲     Forlì-Cesena     618.21    NaN
13         14       +24▲            Lecco     617.98    NaN
14         15       +15▲            Siena     615.83   21.0
15         16        -2▼        Pordenone     615.28    NaN
16         17       -13▼            Aosta     615.03  322.0
17         18        +1▲           Padova     614.13    NaN
18         19        -7▼          Trieste     613.78  312.0
19         20        -5▼          Brescia     610.85    NaN
20         21       -14▼           Modena     607.39    1.0
21         22       +11▲           Varese     606.37    NaN
22         23       +23▲          Mantova     605.33    NaN
23         24        -4▼          Treviso     605.19    NaN
24         25       +12▲         Macerata     602.59    NaN
25         26       -15▼            Parma     602.55   24.0
26         27        +7▲          Ravenna     601.04   11.0
27         28       -12▼    Reggio Emilia     598.87   12.0
28         29       +19▲             Lodi     597.89    NaN
29         30        -1▼          Sondrio     597.64  224.0
30         31          -            Prato     595.97    NaN
31         32       +10▲           Novara     595.00    NaN
32         33        -7▼         Piacenza     594.33  111.0
33         34       -13▼             Pisa     593.77    NaN
34         35       -11▼           Ancona     591.50    NaN
35         36       -30▼          Firenze     590.45   11.0
36         37        +2▲            Cuneo     588.84    NaN
37         38       -13▼  Pesaro e Urbino     588.54    NaN
38         39       -11▼          Gorizia     588.07   14.0
39         40        +9▲          Perugia     585.85    NaN
40         41        +4▲           Arezzo     581.65    1.0
41         42        +9▲           Rimini     579.98    NaN
42         43          -            Pavia     579.46    NaN
43         44       -21▼         Cagliari     578.10    NaN
44         45        -1▼          Belluno     576.79  225.0
45         46       -14▼          Venezia     572.31    NaN
46         47        +3▲            Fermo     571.72    NaN
47         48       +14▲            Terni     568.88    NaN
48         49        +6▲             Asti     568.83    NaN
49         50        +2▲           Biella     568.02    NaN

In [11]:
# Trova le province comuni tra i due dataframe
province_comuni = qualità[qualità['provincia'].isin(clima['provincia'])]['provincia'].reset_index(drop=True)
province_comuni

0             Bolzano
1       Ascoli Piceno
2        Forlì-Cesena
3               Siena
4               Aosta
5             Trieste
6            Macerata
7             Ravenna
8              Ancona
9               Cuneo
10    Pesaro e Urbino
11            Gorizia
12            Perugia
13             Rimini
14           Cagliari
15            Venezia
16              Fermo
Name: provincia, dtype: object

In [12]:
# Crea un DataFrame con le province comuni e le posizioni in classifica per clima e qualità
df_comuni = province_comuni.to_frame().rename(columns={'provincia': 'provincia'})
df_comuni['posizione_clima'] = df_comuni['provincia'].map(clima.set_index('provincia')['posizione'])
df_comuni['posizione_qualità'] = df_comuni['provincia'].map(qualità.set_index('provincia')['posizione'])
df_comuni

          provincia  posizione_clima  posizione_qualità
0           Bolzano               31                  3
1     Ascoli Piceno               18                 10
2      Forlì-Cesena               46                 13
3             Siena               30                 15
4             Aosta               24                 17
5           Trieste                7                 19
6          Macerata               20                 25
7           Ravenna               40                 27
8            Ancona                6                 35
9             Cuneo               44                 37
10  Pesaro e Urbino               10                 38
11          Gorizia               41                 39
12          Perugia               22                 40
13           Rimini               13                 42
14         Cagliari               26                 44
15          Venezia               15                 46
16            Fermo               19                 47

In [17]:
df_comuni.sort_values(by='posizione_clima')
df_comuni_clima =df_comuni.sort_values(by='posizione_clima')
df_comuni_clima

          provincia  posizione_clima  posizione_qualità
8            Ancona                6                 35
5           Trieste                7                 19
10  Pesaro e Urbino               10                 38
13           Rimini               13                 42
15          Venezia               15                 46
1     Ascoli Piceno               18                 10
16            Fermo               19                 47
6          Macerata               20                 25
12          Perugia               22                 40
4             Aosta               24                 17
14         Cagliari               26                 44
3             Siena               30                 15
0           Bolzano               31                  3
7           Ravenna               40                 27
11          Gorizia               41                 39
9             Cuneo               44                 37
2      Forlì-Cesena               46                 13

In [22]:
# Crea una colonna 'scarto' come differenza tra posizione_clima e l'indice del DataFrame
df_comuni_clima = df_comuni_clima.copy()
df_comuni_clima['scarto'] =  df_comuni.index - df_comuni_clima.index

# Ordina il DataFrame in base alla colonna 'scarto'
df_comuni_clima_sorted = df_comuni_clima.sort_values(by='scarto')
df_comuni_clima_sorted

          provincia  posizione_clima  posizione_qualità  scarto
15          Venezia               15                 46     -11
13           Rimini               13                 42     -10
16            Fermo               19                 47     -10
8            Ancona                6                 35      -8
10  Pesaro e Urbino               10                 38      -8
5           Trieste                7                 19      -4
14         Cagliari               26                 44      -4
12          Perugia               22                 40      -4
6          Macerata               20                 25       1
11          Gorizia               41                 39       3
1     Ascoli Piceno               18                 10       4
4             Aosta               24                 17       5
9             Cuneo               44                 37       6
7           Ravenna               40                 27       6
3             Siena               30                 15       8
0           Bolzano               31                  3      12
2      Forlì-Cesena               46                 13      14